version: "2"

run:
  timeout: 5m

linters:
  enable:
    # General
    - depguard
    - gomoddirectives
    - nolintlint

    # Code Quality
    - gosec
    - revive
    - nestif
    - nakedret
    - gocritic
    - godot
    - godox
    - gocyclo
    - gocognit
    - goconst
    - unconvert
    - unparam
    - asciicheck
    - bodyclose
    - dupl
    - funlen
    - dogsled
    - importas
    - nilerr
    - errorlint
    - prealloc
    - durationcheck
    - testableexamples

  settings:
    depguard:
      rules:
        main:
          files:
            - "**/*.go"
          allow:
            - $gostd
            - github.com/ovirt/go-ovirt
            - github.com/dyudin0821/go-ovirt-client/v3
            - github.com/ovirt/go-ovirt-client-log/v3
            - github.com/google/uuid

    govet:
      enable-all: true
      # check-shadowing: false
      disable:
        - fieldalignment
        - shadow
